### ISSUE TITLE
Define OpenHIM standard configuration to be used for TWG 2.0

### ISSUE THREAD

**Issue by andrablaj** [medic/interoperability#1]
Define and share OpenHIM (see [OpenHIM Core Component](https://github.com/jembi/openhim-core-js)) standard configuration for TWG 2.0 project. Participating CHISs need to agree is correct, accurate and inclusive of required features, in the context of  Loss to Follow Up workflow.

Subtasks:

- [ ] Initial commit with Instant OpenHIE's core package
- [ ] Define FHIR resources required
- [ ] Add eslint to the mediator directory
- [ ] Run all services require with one command

**Comment by samuelimoisili** [comment]
I forgot to link PR #3 to this ticket. It's has been merged.
