### ISSUE TITLE
Set up an instance running the configuration in this repo

### ISSUE THREAD

**Issue by njogz** [medic/interoperability#29]
Linkes to [this issue](https://github.com/medic/medic-infrastructure/issues/562)

**Comment by andrablaj** [comment]
@njogz is this issue the same as [this issue](https://github.com/medic/medic-infrastructure/issues/562)?

**Comment by andrablaj** [comment]
[Related ticket](https://github.com/medic/medic-infrastructure/issues/579)

**Comment by andrablaj** [comment]
Another [related ticket](https://github.com/medic/medic-infrastructure/issues/587).

**Comment by andrablaj** [comment]
From @njogz :

> the OpenHIM and CHT instances for testing interoperability are currently working and you can try out the LTFU workflow with them.
> The CHT instance can be found at https://interop-cht-test.dev.medicmobile.org/. You can find credentials for an admin and a chw in 1password in the interoperability vault.
> The openHIM instance can be accessed at https://interoperability.dev.medicmobile.org/ with credentials also in 1password. Please note that the payload to initiate a follow up should be sent to https://interoperability.dev.medicmobile.org:5001/mediator/service-request.
