### ISSUE TITLE
Set up Github Actions to run tests for branches and PRs

### ISSUE THREAD

**Issue by njogz** [medic/interoperability#50]

**Comment by andrablaj** [comment]
@njogz is this the same as https://github.com/medic/interoperability/issues/15? If yes, I suggest to close the other ticket

**Comment by andrablaj** [comment]
Either way works as long as we don't keep duplicated issues. I will let you make the call on this one. 😊

**Comment by andrablaj** [comment]
Closing as duplicate of https://github.com/medic/interoperability/issues/15
